using Autodesk.DesignScript.Geometry;
using Autodesk.DesignScript.Runtime;
using DSCore;
using Dynamo.Graph.Nodes;

namespace DynaShape.ZeroTouch.GeometryBinders;

/// <summary>
/// Wrapper class for MeshBinder
/// </summary>
public class MeshBinder
{
    private MeshBinder(){}


    /// <summary>
    /// Create a MeshBinder.
    /// </summary>
    /// <param name="mesh">The mesh generated by MeshToolkit.</param>
    /// <param name="color">An optional color to preview the circle geometry.</param>
    /// <returns name="meshBinder"></returns>
    [NodeCategory("Create")]
    public static DynaShape.GeometryBinders.MeshBinder ByMesh(
        Autodesk.Dynamo.MeshToolkit.Mesh mesh,
        [DefaultArgument("null")] Color color)
    {
        var binder = TracingUtils.GetObjectFromTrace<DynaShape.GeometryBinders.MeshBinder>();

        binder.Initialize(
            mesh,
            color?.ToColor4() ?? DynaShapeDisplay.DefaultMeshFaceColor);

        return binder;
    }
}