using Autodesk.DesignScript.Geometry;
using Autodesk.DesignScript.Runtime;
using DSCore;
using Dynamo.Graph.Nodes;

namespace DynaShape.ZeroTouch.GeometryBinders;

/// <summary>
/// Wrapper class for MeshBinder
/// </summary>
public class MeshBinder
{
    private MeshBinder(){}

    /// <summary>
    /// Create a MeshBinder to preview Mesh geometry.
    /// </summary>
    /// <param name="mesh">The Mesh generated by Dynamo geometry.</param>
    /// <param name="color">An optional color to preview the circle geometry.</param>
    /// <returns name="meshBinder"></returns>
    [NodeCategory("Create")]
    public static DynaShape.GeometryBinders.MeshBinder ByMesh(
        Mesh mesh,
        [DefaultArgument("null")] Color color)
    {
        return new DynaShape.GeometryBinders.MeshBinder(
            mesh,
            color?.ToColor4() ?? DynaShapeDisplay.DefaultMeshFaceColor);
    }
    /// <summary>
    /// Create a MeshBinder to preview Mesh geometry.
    /// </summary>
    /// <param name="toolkitMesh">The mesh generated by MeshToolkit.</param>
    /// <param name="color">An optional color to preview the circle geometry.</param>
    /// <returns name="meshBinder"></returns>
    [NodeCategory("Create")]
    public static DynaShape.GeometryBinders.MeshBinder ByToolkitMesh(
        Autodesk.Dynamo.MeshToolkit.Mesh toolkitMesh,
        [DefaultArgument("null")] Color color)
    {
        return new DynaShape.GeometryBinders.MeshBinder(
            toolkitMesh,
            color?.ToColor4() ?? DynaShapeDisplay.DefaultMeshFaceColor);
    }
}