using Autodesk.DesignScript.Runtime;
using DSCore;
using Dynamo.Graph.Nodes;
using HelixToolkit.SharpDX.Core;

namespace DynaShape.ZeroTouch.GeometryBinders;

/// <summary>
/// Wrapper class for TexturedMeshBinder
/// </summary>
public class TexturedMeshBinder
{
    private TexturedMeshBinder(){}

    /// <summary>
    /// Create a TexturedMeshBinder.
    /// </summary>
    /// <param name="toolkitMesh">The mesh generated by MeshToolkit.</param>
    /// <param name="color">An optional color to preview the circle geometry.</param>
    /// <param name="textureFileName">A texture file to apply to the given ToolkitMesh.</param>
    /// <param name="textureCoordinates">The coordinates to extract from the texture file.</param>
    /// <returns name="texturedMeshBinder"></returns>
    [NodeCategory("Create")]
    public static DynaShape.GeometryBinders.TexturedMeshBinder ByToolkitMeshAndTexture(
        Autodesk.Dynamo.MeshToolkit.Mesh toolkitMesh,
        [DefaultArgument("null")] Color color,
        string textureFileName,
        Vector2Collection textureCoordinates)
    {
        return new DynaShape.GeometryBinders.TexturedMeshBinder(
            toolkitMesh,
            color?.ToColor4() ?? DynaShapeDisplay.DefaultMeshFaceColor,
            textureFileName,
            textureCoordinates);
    }
}